apiVersion: v1
appVersion: "2.1.7"
description: A Helm chart for running nats cluster in Kubernetes
name: nats
version: 0.0.3
sources:
  - https://github.com/nats-io/nats-operator
  - https://store.docker.com/images/nats
