apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dictyuser-postgres.name" . }}
  labels:
    app: {{ template "dictyuser-postgres.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgres.dictyuser.password:  {{required "A value for .Values.postgresPassword  is required" .Values.postgresPassword | b64enc | quote }}
  dictyuser.password: {{required "A value for .Values.dictyuserPassword is required" .Values.dictyuserPassword | b64enc | quote }}
