apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }} 
  #annotations:
    #"helm.sh/hook": pre-install
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgres.dictymine.user: {{  .Values.postgresUser | quote }}
  postgres.dictymine.database: {{  .Values.postgresDatabase | quote }}
  dictymine.user: {{ .Values.dictymineUser | quote }}
  dictymine.database: { .Values.dictymineDatabase | quote }} 
  dictymine.items.database: {{  .Values.dictymineItemsDatabase | quote }} 
  dictymine.userprofile.database: {{ .Values.dictymineUserProfileDatabase | quote }} 
