# This is a pre-install hook
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  # The following defines it as a pre-install hook. The name is given for
  # better understanding, it actually could be anything.
  #annotations:
    #"helm.sh/hook": pre-install
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.postgresPassword }}
  postgres.dictymine.password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres.dictymine.password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.dictyminePassword }}
  dictymine.password: {{ .Values.dictyminePassword | b64enc | quote }}
  {{- else }}
  dictymine.password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
