apiVersion: v1
kind: Service
metadata:
  name: {{ default "postgres" .Values.service.name }}  
  labels:
    app: {{ template "fullname" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
    heritage: {{.Release.Service | quote}} 
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
{{- end }}
spec:
  ports:
  - name: {{ default "dictymine-backend" .Values.service.name }}  
    port: {{ default 5434 .Values.service.port }}
    targetPort: {{ default "dictymine-backend" .Values.service.name }}   
  selector:
    app: {{ template "fullname" . }}
    type: {{ default "nodePort" .Values.service.type }}
