apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}  
  labels:
    app: {{ template "fullname" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
    heritage: {{.Release.Service | quote}} 
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
{{- end }}
spec:
  type: {{ Values.service.type | quote }}
  ports:
  - name: {{ .Values.service.name | quote }}  
    port: {{ .Values.service.port | quote }}
    targetPort: {{ .Values.service.name | quote }}   
  selector:
    app: {{ template "fullname" . }}
