# Default values for local-storage.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: gcr.io/k8s-minikube/storage-provisioner
  tag: v1.8.1
  pullPolicy: IfNotPresent

storage:
# name that will be used in chart, do not change
  name: host-storage
# absolute host path, required for storage(mandatory)
#  path: /mnt/docker/kubestorage
# default storage class name
  className: local-storage

