apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name | quote}}
  labels:
    app: {{.Release.Name | quote}}
    heritage: {{.Release.Service | quote}} 
      # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{default 1 .Values.replicas | quote}}
  template:
    metadata:
      labels:
        app: {{.Release.Name | quote}}
        group: {{.Values.group | quote}}
        provider: {{.Values.provider | quote}}
        mode: {{.Values.mode |quote}}
    spec:
      containers:
        - name: {{.Release.Name |quote}}
          image: "{{.Values.dockerNamespace}}/authserver:{{.Values.dockerTag}}"
          command: ["/bin/bash", "-c"]
          args: ["app run --pkey /etc/authserver/jwt-public-key --config /etc/authserver/client-private-keys  --prkey /etc/authserver/jwt-private-key"]
          imagePullPolicy: {{.Values.pullPolicy |quote}}
          ports:
            - name: {{.Values.portName | quote}}
              containerPort: {{.Values.portNum | quote}}
          volumeMounts:
            - name: auth-secrets
              mountPath: /etc/authserver
              readOnly: true
      volumes:
        - name: auth-secrets
          secret: 
            secretName: {{.Values.secretName}}
