apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name | quote}}
  labels:
    heritage: {{.Release.Service | quote}} 
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: {{.Values.provider | quote}}
    group: {{.Values.group | quote}}
    mode: {{.Values.mode | quote}}
spec:
  type: NodePort
  ports:
    # The port below where the service should run 
    - port: {{.Values.portNum | quote}}
    # The target port(pod) where it should proxy(map) to
      targetPort: {{.Values.portName | quote}}
  selector:
    provider: {{.Values.provider | quote}}
