apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name | quote}}
  labels:
    heritage: {{.Release.Service | quote}} 
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: {{.provider | quote}}
    group: {{.group | quote}}
    mode: {{.mode | quote}}
specs:
  ports:
    - port: {{.portNum}}
      targetPort: {{.portName | quote}}
  selector:
    provider: {{.provider | quote}}
