# Default values for dictybase-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    # cert-manager.io/issuer: issuer-name
  # hosts:
  #  - name: betaapi.random.local
  #    paths:
  #      - path: /contents
  #        serviceName: content-api
  #        servicePort: 9555
  #      - path: /identities
  #        serviceName: identity-api
  #        servicePort: 9560
  #  - name: betatoken.random.local
  #    paths:
  #      - path: /tokens
  #        serviceName: authserver
  #        servicePort: 9996
  # tls:
  #  - secretName: example-local-tls
  #    hosts:
  #     - example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
