apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{.Release.Name}}-backup-volume"
  labels: 
    heritage: {{.Release.Service | quote}} 
    group: {{.Values.group | quote}}
    provider: {{.Values.backup.provider | quote}}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  capacity:
    storage: {{.Values.backup.size | quote}}
  accessModes:
    - {{.Values.mode | quote}}
  hostPath:
    path: {{.Values.backup.path | quote}}
  persistentVolumeReclaimPolicy: {{.Values.policy | quote}}
