# Default values for dictyuser-schema.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: dictybase/dictyuser-schema
  tag: 2.1.0
  pullPolicy: IfNotPresent

# ConfigMaps and secrets keys for configuring chado database access.
# It should match the configMaps, secrets and their key names deployed with
# dictyuser-postgres chart.
dictyuserPostgres:
  configMap:
    name: dictycontent-postgres
    user: dictyuser.user
    database: dictyuser.database
  secrets:
    name: dictycontent-postgres
    password: dictyuser.password


