apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dictybase-configuration.name" . }} 
  labels:
    app: {{ template "dictybase-configuration.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  endpoints.organism: "{{ .Values.endpoints.organism }}"
  endpoints.publication: "{{ .Values.endpoints.publication }}"
  eventMessenger.github.owner: "{{ .Values.eventMessenger.github.owner }}"
  eventMessenger.github.repository: "{{ .Values.eventMessenger.github.repository }}"
  eventMessenger.email.domain: "{{ .Values.eventMessenger.email.domain }}"
  eventMessenger.email.sender: "{{ .Values.eventMessenger.email.sender }}"
  eventMessenger.email.senderName: "{{ .Values.eventMessenger.email.senderName }}"
  arangodb.user: "{{ .Values.arangodb.user }}"
{{- range .Values.arangodb.databases }}
 {{ printf " arangodb.%s" .app }}: {{ .name | quote }}
{{- end -}}
