apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dictybase-configuration.name" . }} 
  labels:
    app: {{ template "dictybase-configuration.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  slack.channel: "{{ .Values.slack.channel }}"
  slack.endpoint: "{{ .Values.slack.endpoint }}"
  arangodb.user: "{{ .Values.arangodb.user }}"
{{- range .Values.arangodb.databases }}
 {{ printf " arangodb.%s" .app }}: {{ .name | quote }}
{{- end -}}
