apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dictybase-configuration.name" . }}
  labels:
    app: {{ template "dictybase-configuration.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  arangodb.password:  {{required "A value for .Values.arangodb.password  is required" .Values.arangodb.password | b64enc | quote }}
  slack.token: {{required "A value for .Values.slack.token is required" .Values.slack.token | b64enc | quote }}
