{{- if not .Values.backend.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baserow.backend.secretName" . }}
data:
  jwt-signing-key: {{ .Values.backend.config.jwtSigningKey | default (randAlphaNum 32) | b64enc }}
  secret-key: {{ .Values.backend.config.secretKey | default (randAlphaNum 32) | b64enc }}
{{- end }}
