{{- if and (not .Values.backend.config.aws.existingSecret) (or (.Values.backend.config.aws.accessKeyId) (.Values.backend.config.aws.secretAccessKey)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baserow.backend.aws.secretName" . }}
data:
  {{- if .Values.backend.config.aws.accessKeyId }}
  access-key-id: {{ .Values.backend.config.aws.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.backend.config.aws.secretAccessKey }}
  secret-access-key: {{ .Values.backend.config.aws.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}
