apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.name }}-tls
  issuerRef:
    kind: Issuer
    name: {{ .Values.issuer.name }}
  dnsNames:
    {{- range .Values.certificate.domains }}
    - {{ . }}
    {{- end}}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          {{- range .Values.certificate.domains }}
          - {{ . }}
          {{- end}}
