# Default values for chado-postgres.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
group: database
provider: chado
mode: standalone
dockerNamespace: dictybase
ImageName: chado-postgres
dockerTag: 9.4-dev-rw
portName: postgres
portNum: 5432 
tier: dev
secretName: postgres-credentials
serviceType: NodePort
dataDir: /var/lib/postgresql/data
claim:
  name: local-database-claim
