# Default values for chado-postgres.
group: database
provider: chado
mode: standalone
image: 
## postgres image repository
  repository: dictybase/chado-postgres
## chado-postgres image version
## ref: https://hub.docker.com/r/dictybase/chado-postgres/
##
  tag: v1.0.2
## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  #pullPolicy:

## superuser and database
postgresUser: postgres
postgresDatabase: postgres

## chado user and database
chadoUser: chadomaster
chadoDatabase: dictychado

## Persist data to a persitent volume
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 4Gi
  subPath: postgresql-db

metrics:
  enabled: false
  image: 
    repository: wrouesnel/postgres_exporter
    tag: v0.1.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
#resources:
  #requests:
    #memory: 256Mi
    #cpu: 100m

# Setup for service, don't uncomment rather override it
service:
  name: chado-backend
  type: NodePort


