# Default values for restore-postgres.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
group: data-archive
provider: chado-restore
mode: standalone
dockerNamespace: dictybase
ImageName: postgres-restore
dockerTag: latest
claim: local-database-claim 
dataDir: /restore
stagingDir: /staging
hostDir: /data/staging
archiveName: dictychado.dump
secretName: postgres-credentials
chadoService: chado-postgres
policy: Never
