apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.issuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx