apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "lighthouse-ci.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }} 
      name: {{ .Values.service.name }} 
  selector:
    app.kubernetes.io/name: {{ include "lighthouse-ci.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
