# Default values for dictymine-jetty.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: dictybase/dictymine-jetty
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: dictymine-jetty
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  enabled: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

