# Default values for fake-dsc-server.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
dockerTag: latest 
pullPolicy: IfNotPresent
dockerNamespace: dictybase
provider: fake-api-server
group: api
mode: standalone
portName: fakeapi-port
portNum: 8080
