apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: {{ template "arangodb.name" . }}
  labels:
    app: {{ template "arangodb.name" . }}
    chart: {{ template "arangodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.arangodb }}
  mode: {{ .mode }}
  environment: {{ .environment }}
  storageEnginge: {{ .engine }}
  {{- if ne "Single" .mode }}
  agents:
    count: {{ .agents.count }}
    resources:
      requests:
        storage: {{ .agents.storage }}
  {{- end }}
  dbservers:
    resources:
      requests:
        storage: {{ .dbservers.storage }}
{{- end }}
