apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: {{ template "arangodb.name" . }}
  labels:
    app: {{ template "arangodb.name" . }}
    chart: {{ template "arangodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.arangodb }}
  externalAccess:
    type: {{ .service.type }}
  mode: {{ .mode }}
  environment: {{ .environment }}
  storageEngine: {{ .engine }}
  {{- if ne "Single" .mode }}
  agents:
    count: {{ .agents.count }}
    resources:
      requests:
        storage: {{ .agents.storage }}
  {{- if .dbservers.storageClass }}
    storageClassName: {{ .dbservers.storageClass }}
  {{- end }}
  dbservers:
    count: {{ .dbservers.count }}
    resources:
      requests:
        storage: {{ .dbservers.storage }}
  {{- if .dbservers.storageClass }}
    storageClassName: {{ .dbservers.storageClass }}
  {{- end }}
  {{- end }}
  {{- if eq "Single" .mode }}
  single:
    count: {{ .single.count }}
    resources:
      requests:
        storage: {{ .single.storage }}
  {{- if .single.storageClass }}
    storageClassName: {{ .single.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
