apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: {{ template "arangodb.name" . }}
  labels:
    app: {{ template "arangodb.name" . }}
    chart: {{ template "arangodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.arangodb }}
  externalAccess:
    type: {{ .service.type }}
  mode: {{ .mode }}
  environment: {{ .environment }}
  storageEngine: {{ .engine }}
  {{- if eq "Single" .mode }}
  single:
    volumeClaimTemplate:
      spec:
        accessModes:
          - {{ .dbservers.accessMode }}
        resources:
          requests:
            storage: {{ .single.storage }}
      {{- if .dbservers.storageClass }}
        storageClassName: {{ .dbservers.storageClass }}
      {{- end }}
  {{- end }}
  {{- if ne "Single" .mode }}
  agents:
    count: {{ .agents.count }}
    volumeClaimTemplate:
      spec:
        accessModes:
          - {{ .dbservers.accessMode }}
        resources:
          requests:
            storage: {{ .agents.storage }}
      {{- if .dbservers.storageClass }}
        storageClassName: {{ .dbservers.storageClass }}
      {{- end }}
  dbservers:
    count: {{ .dbservers.count }}
    volumeClaimTemplate:
      spec:
        accessModes:
          - {{ .dbservers.accessMode }}
        resources:
          requests:
            storage: {{ .dbservers.storage }}
      {{- if .dbservers.storageClass }}
        storageClassName: {{ .dbservers.storageClass }}
      {{- end }}
  {{- end }}
{{- end }}