apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nats-operator.name" . }}
  labels:
    app: {{ template "nats-operator.name" . }}
    chart: {{ template "nats-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "nats-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ template "nats-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: MY_POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
