apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:{{ .Values.operator.name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ .Values.operator.name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:{{ .Values.operator.name }}
rules:
  # Allow creating CRDs
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  # Allow all actions on NatsClusters
  - apiGroups:
      - nats.io
    resources:
      - natsclusters
      - natsserviceroles
    verbs: ["*"]
  # Allow actions on basic Kubernetes objects
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
      - services
      - serviceaccounts
      - serviceaccounts/token
      - endpoints
      - events
    verbs: ["*"]
