apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "dictybase-auth-ingress.fullname" . }}
  labels:
    app: {{ template "dictybase-auth-ingress.name" . }}
    chart: {{ template "dictybase-auth-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if .Values.ingress.hosts }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
      {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
      {{- end }}
  {{- end }}
{{- end }}
