apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baserow.backend.wsgi.fullname" . }}
  labels:
    {{- include "baserow.backend.wsgi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.wsgi.autoscaling.enabled }}
  replicas: {{ .Values.backend.wsgi.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.backend.wsgi.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "baserow.backend.wsgi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.wsgi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baserow.backend.wsgi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.wsgi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "baserow.backend.wsgi.serviceAccountName" . }}
      {{- with .Values.backend.wsgi.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "baserow.backend.wsgi.name" . }}
          image: "{{ .Values.backend.wsgi.image.repository }}:{{ .Values.backend.wsgi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.wsgi.image.pullPolicy }}
          workingDir: /baserow
          args:
            - "gunicorn-wsgi"
            - "--timeout"
            - "60"
          env:
            - name: MIGRATE_ON_STARTUP
              value: "false"
            # Baserow Backend Settings
            - name: BASEROW_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.backend.secretName" . | quote }}
                  key: jwt-signing-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.backend.secretName" . | quote }}
                  key: secret-key
            # Baserow Email Settings
            {{- if .Values.backend.config.email.smtp }}
            - name: EMAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.backend.email.secretName" . | quote }}
                  key: email-password
            {{- end }}
            # Baserow File Upload Settings
            {{- if or .Values.backend.config.aws.accessKeyId .Values.backend.config.aws.existingSecret }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.backend.aws.secretName" . | quote }}
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.backend.aws.secretName" . | quote }}
                  key: secret-access-key
            {{- end }}
            # Database Settings
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.postgresql.secretName" . | quote }}
                  key: {{ include "baserow.postgresql.userPasswordKey" . | quote }}
            # Redis Settings
            {{- if eq (include "baserow.redis.auth.enabled" .) "true" }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "baserow.redis.secretName" . | quote }}
                  key: {{ include "baserow.redis.userPasswordKey" . | quote }}
            {{- end -}}
            {{- range .Values.backend.wsgi.extraEnv }}
            {{- if and (.name) (.value) }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "baserow.fullname" . }}
            - configMapRef:
                name: {{ include "baserow.backend.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.wsgi.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "/baserow/backend/docker/docker-entrypoint.sh backend-healthcheck"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "/baserow/backend/docker/docker-entrypoint.sh backend-healthcheck"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
          {{- with .Values.backend.wsgi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.wsgi.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: media
              mountPath: {{ .Values.backend.config.media.root | quote }}
          {{- end }}
      {{- with .Values.backend.wsgi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.wsgi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.wsgi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "baserow.backend.pvcName" . }}
      {{- end }}
