{{- if .Values.backend.wsgi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baserow.backend.wsgi.serviceAccountName" . }}
  labels:
    {{- include "baserow.backend.wsgi.labels" . | nindent 4 }}
  {{- with .Values.backend.wsgi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
