# Default values for dictycontent-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
group: api-server
provider: dictycontent
mode: standalone
replicaCount: 1
image:
  repository: dictybase/modware-content
  tag: 0.0.4
  pullPolicy: IfNotPresent
# ConfigMaps and secrets keys for configuring backend database access.
# It should match the configMaps, secrets and their key names deployed with
# dictycontent-postgres chart.
dictyContentPostgres:
  configMap:
    name: dictycontent-postgres
    user: dictycontent.user
    database: dictycontent.database
  secrets:
    name: dictycontent-postgres
    password: dictycontent.password
service:
  name: content-api
  type: NodePort
  port: 9555
# resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
# nodeSelector: {}
healthCheck:
  # configure liveness probes for 
  # container
  path: "/healthz"
  delay: 6

