# Default values for issuer-certificate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# namespace: dictybase

issuer:
  # for testing use https://acme-staging-v02.api.letsencrypt.org/directory
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  # name: dictybase-eric-dev
  # email: user@example.com