apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Values.sensor.name }}
  namespace: {{ .Values.namespace }}
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: {{ .Values.serviceAccount }}
  dependencies:
    - name: "{{ .Values.gateway.name }}:{{ .Values.hooks.repo }}"
  eventProtocol:
    type: {{ .Values.gateway.eventProtocol.type }}
    http:
      port: {{ .Values.gateway.eventProtocol.port | quote }}
  triggers:
    - template:
        name: "github-{{ .Values.hooks.repo | replace "-" "" }}-workflow-trigger"
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          url:
            path: {{ .Values.sensor.workflow }}
            verifycert: {{ .Values.sensor.verifyCert }}
      resourceParameters:
        - src:
            event: "{{ .Values.gateway.name }}:{{ .Values.hooks.repo }}"
            path: "repository.clone_url"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "{{ .Values.gateway.name }}:{{ .Values.hooks.repo }}"
            path: "head_commit.id"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "{{ .Values.gateway.name }}:{{ .Values.hooks.repo }}"
            path: "repository.name"
          dest: spec.arguments.parameters.2.value
