apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }} 
  #annotations:
    #"helm.sh/hook": pre-install
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgres.user: {{ .Values.postgresUser | quote }}
  postgres.database: {{ .Values.postgresDatabase | quote }}
  chado.user: {{  .Values.chadoUser | quote }}
  chado.database: {{ .Values.chadoDatabase | quote }} 
