apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name | quote}}
  labels:
    heritage: {{.Release.Service | quote}} 
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: {{.Values.provider | quote}}
    group: {{.Values.group | quote}}
    mode: {{.Values.mode | quote}}
spec:
  type: {{.Values.serviceType | quote}}
  ports:
    - port: {{.Values.portNum | quote}}
      targetPort: {{.Values.portName | quote}}
  selector:
    provider: {{.Values.provider | quote}}
    group: {{.Values.group | quote}}
    mode: {{.Values.mode | quote}}
    app: {{.Release.Name | quote}}

