apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dictycontent-postgres.name" . }}
  labels:
    app: {{ template "dictycontent-postgres.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgres.dictycontent.password:  {{required "A value for .Values.postgresPassword  is required" .Values.postgresPassword | b64enc | quote }}
  dictycontent.password: {{required "A value for .Values.dictycontentPassword is required" .Values.dictycontentPassword | b64enc | quote }}
