# Default values for dictycontent-schema.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: dictybase/dictycontent-schema
  tag: 1.1.0
  pullPolicy: IfNotPresent

# ConfigMaps and secrets keys for configuring backend database access.
# It should match the configMaps, secrets and their key names deployed with
# dictycontent-postgres chart.
dictyContentPostgres:
  configMap:
    name: dictycontent-postgres
    user: dictycontent.user
    database: dictycontent.database
  secrets:
    name: dictycontent-postgres
    password: dictycontent.password


